### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by CorruptData** [WJLiddy/ad2#1]
Testing the issue system on here.
Also game crashed while fighting bandits in field.
Console says:
Mon Mar 16 03:20:03 EDT 2015 ERROR:null
java.util.ConcurrentModificationException
	at java.util.LinkedList$ListItr.checkForComodification(Unknown Source)
	at java.util.LinkedList$ListItr.next(Unknown Source)
	at liddyjack.ad2.LivingUnit.pickUpDosh(LivingUnit.java:471)
	at liddyjack.ad2.LivingUnit.idleLogic(LivingUnit.java:438)
	at liddyjack.ad2.LivingUnit.notDeadlogic(LivingUnit.java:427)
	at liddyjack.ad2.LivingUnit.logic(LivingUnit.java:241)
	at liddyjack.ad2.World.doPlayerLogic(World.java:1073)
	at liddyjack.ad2.World.logic(World.java:311)
	at liddyjack.ad2.Adventure.update(Adventure.java:226)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:657)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
	at liddyjack.ad2.Adventure.main(Adventure.java:274)
Mon Mar 16 03:20:03 EDT 2015 ERROR:Game.update() failure - check the game code.
org.newdawn.slick.SlickException: Game.update() failure - check the game code.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:669)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
	at liddyjack.ad2.Adventure.main(Adventure.java:274)

**Comment by WJLiddy** [comment]
Fixed
